---

- name: install unbound (DNS Cache server)
  yum:
    name: unbound
    state: installed

- name: copy config
  template:
    src: unbound.conf.jinja2
    dest: /etc/unbound/unbound.conf
  notify: reconfig unbound

- name: enable unbound auto start on bootup
  systemd:
    name: unbound
    state: started
    enabled: yes
